<?xml version="1.0" encoding="utf-8"?><Database Name="cryptocurrency" Class="LinqToSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-6HUM6MNH;Initial Catalog=cryptocurrency;Integrated Security=True" SettingsObjectName="SQLCryptoCurrency.Properties.Settings" SettingsPropertyName="cryptocurrencyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CryptoCoin" Member="CryptoCoins">
    <Type Name="CryptoCoin">
      <Column Name="CoinName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoinSymbol" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CoinRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume24H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PercentChange24H" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CryptoCoin_UserCoin" Member="UserCoins" ThisKey="CoinName" OtherKey="CoinName" Type="UserCoin" />
    </Type>
  </Table>
  <Table Name="dbo.UserCoins" Member="UserCoins">
    <Type Name="UserCoin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoinName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CryptoCoin_UserCoin" Member="CryptoCoin" ThisKey="CoinName" OtherKey="CoinName" Type="CryptoCoin" IsForeignKey="true" />
      <Association Name="User_UserCoin" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="User_UserCoin" Member="UserCoins" ThisKey="ID" OtherKey="UserID" Type="UserCoin" />
    </Type>
  </Table>
</Database>